const tramites = {
    "ASILO": {
        "días": {
            1: "Hola 😊, qué gusto saludarte. ¿Cómo te has sentido al pensar en iniciar tu trámite de asilo?",
            2: "¡Buenos días! Me alegra saludarte. ¿Qué te inspiró a considerar solicitar asilo en Estados Unidos?",
            3: "Hola, ¿qué parte del proceso te genera más curiosidad o dudas en este momento?",
            4: "¡Hola!, ¿Qué te gustaría saber sobre los pasos iniciales para presentar tu solicitud?",
            5: "Hola 😊, ¿qué te motivó a buscar protección a través del asilo?",
            6: "¡Buenos días! ¿Qué esperas lograr con este proceso para ti o tu familia?",
            7: "Hola, ¿cómo ha sido tu experiencia desde que pensaste en solicitar asilo?",
            8: "¡Hola!, ¿Qué información te gustaría tener más clara antes de iniciar?",
            9: "Hola, ¿qué tipo de ayuda consideras que te sería más útil ahora mismo?",
            10: "Hola 😊, ¿cómo te imaginas el momento en que tu caso de asilo esté aprobado?"
        },
        "semana_1": {
            11: "Hola, ¿qué avances lograste desde la última vez en tu trámite de asilo?",
            12: "¡Buenos días! ¿Qué aspecto te gustaría comprender mejor del proceso?",
            13: "Hola, ¿qué documentación ya tienes lista para tu caso?",
            14: "¡Hola!, ¿Qué esperas del acompañamiento profesional durante tu solicitud?",
            15: "Hola, ¿qué parte del trámite te resulta más confusa hasta ahora?",
            16: "Hola, ¿cómo te gustaría que te apoyemos durante esta etapa?",
            17: "¡Buenos días! ¿Qué obstáculos sientes que te detienen para avanzar con tu caso?",
            18: "Hola, ¿qué información te ayudaría a sentirte más seguro para continuar?",
            19: "¡Hola!, ¿Qué te gustaría resolver antes de dar el siguiente paso?",
            20: "Hola, ¿qué día te gustaría retomar el proceso de tu solicitud?"
        },
        "semana_2_3": {
            21: "Hola, ¿qué avances has tenido últimamente en tu caso?",
            22: "¡Buenos días! ¿Qué parte del trámite te gustaría reforzar antes de enviar tu solicitud?",
            23: "Hola, ¿qué detalles te gustaría revisar sobre tu declaración personal?",
            24: "¡Hola!, ¿Qué información adicional te ayudaría a sentirte preparado?",
            25: "Hola, ¿cómo te sientes respecto a tu elegibilidad actual?",
            26: "¡Buenos días! ¿Qué pasos te gustaría priorizar este mes?",
            27: "Hola, ¿cómo te gustaría que te apoyemos en esta etapa?",
            28: "Hola, ¿qué resultado esperas lograr con la ayuda de nuestro equipo?",
            29: "¡Hola! 😊 ¿Qué te gustaría conversar hoy sobre tu proceso de asilo?",
            30: "Hola, ¿qué aspecto crees que podríamos resolver juntos para avanzar?"
        },
        "mes_1": {
            31: "Hola 😊, ¿cómo ha evolucionado tu caso de asilo hasta ahora?",
            32: "¡Buenos días 🌡! ¿Qué parte del proceso te gustaría acelerar o mejorar?",
            33: "Hola, ¿cómo te sientes con la documentación que ya tienes lista?",
            34: "Hola, ¿qué información consideras importante revisar antes de tu próxima cita?",
            35: "Hola 😉, ¿cómo podemos hacer que tu proceso sea más sencillo y claro?",
            36: "¡Hola! ¿Qué parte te gustaría que analicemos más a fondo?",
            37: "Hola, ¿cómo describirías tu experiencia en este proceso hasta hoy?",
            38: "¡Buenos días 🌡! ¿Qué meta te gustaría alcanzar este mes respecto a tu caso?",
            39: "Hola, ¿qué preguntas tienes sobre el avance o seguimiento de tu trámite?",
            40: "Hola, ¿qué aspecto te gustaría mejorar o entender mejor?"
        },
        "mes_2_3": {
            41: "Hola, ha pasado un tiempo. ¿Cómo describirías tu avance en el trámite desde entonces?",
            42: "¡Hola! ¿Qué resultados te gustaría obtener en los próximos meses?",
            43: "Hola 😉, ¿qué cambios has notado en tu caso o en tu situación desde que empezaste?",
            44: "¡Buenos días 🌡! ¿Qué nuevos pasos consideras que te ayudarían a avanzar más rápido?",
            45: "Hola 😊, ¿qué tipo de apoyo te gustaría recibir en esta etapa?",
            46: "Hola 😉, ¿cómo te has sentido con el proceso de tu asilo últimamente?",
            47: "¡Hola!, ¿Qué esperas lograr antes de que termine este mes con tu trámite?",
            48: "Buenos días, ¿qué dudas te gustaría aclarar sobre el seguimiento de tu caso?",
            49: "Hola, ¿qué paso te falta completar para sentir que estás avanzando?",
            50: "Hola, ¿qué cambios te gustaría hacer para fortalecer tu caso?"
        },
        "mes_4_5": {
            51: "Hola, ¿cómo has estado? ¿Qué te gustaría retomar de tu trámite de asilo?",
            52: "¡Buenos días! ¿Qué novedades has tenido desde la última vez que hablamos?",
            53: "Hola, ¿qué crees que te ayudaría a continuar tu proceso con más confianza?",
            54: "Hola, ¿qué parte del trámite te gustaría revisar primero si retomamos hoy?",
            55: "¡Hola!, ¿Qué te inspiró a comenzar tu solicitud y qué te gustaría lograr ahora?",
            56: "Buenos días, con solo $200 puedes retomar tu proceso y seguir avanzando. ¿Qué paso te gustaría iniciar?",
            57: "Hola, ¿cómo te sientes respecto a continuar con tu caso?",
            58: "¡Hola! Me alegra saludarte. ¿Qué información te gustaría que te actualice para seguir adelante?",
            59: "Hola, ¿qué objetivo tienes actualmente con tu trámite de asilo?",
            60: "Buenos días, ¿qué te haría sentir acompañado y seguro durante tu proceso?"
        },
        "valor": {
            61: "Sabías que iniciar tu asilo correctamente puede ayudarte a obtener tu permiso de trabajo en menos tiempo?",
            62: "Cuando preparas bien tu declaración personal, aumentan tus posibilidades de éxito en la entrevista.",
            63: "Mantener tus documentos actualizados demuestra compromiso con tu caso y mejora tu credibilidad ante USCIS.",
            64: "El acompañamiento profesional te ahorra errores que podrían retrasar tu caso varios meses.",
            65: "El asilo no solo protege tus derechos, también puede abrir la puerta a beneficios migratorios a futuro.",
            66: "Cada caso de asilo es único; por eso trabajamos contigo paso a paso para construir una solicitud sólida.",
            67: "Acompañarte en este proceso es nuestra especialidad: te ayudamos a presentar tu caso con claridad y confianza.",
            68: "Prepararte bien para la entrevista de asilo puede marcar la diferencia entre la aprobación o el rechazo.",
            69: "Saber cuándo solicitar tu carta de reloj te permite planificar mejor tu permiso de trabajo.",
            70: "Muchos solicitantes desconocen que pueden evitar retrasos solo con mantener su dirección actualizada ante USCIS.",
            71: "Con un acompañamiento adecuado, puedes presentar tu caso sin estrés y con la documentación correcta.",
            72: "Nuestro equipo te ayuda a identificar qué pruebas fortalecerán tu declaración personal.",
            73: "Al iniciar tu trámite con nosotros, te guiamos hasta que tu solicitud esté completamente presentada.",
            74: "El asilo es un derecho humano y un proceso que requiere responsabilidad y asesoría profesional.",
            75: "Cuando confías tu caso a expertos, aumentas tus posibilidades de éxito y tranquilidad.",
            76: "Tener una carta de reloj activa te permite solicitar tu permiso de trabajo a tiempo.",
            77: "Con solo $200 puedes recibir orientación personalizada para iniciar tu caso correctamente.",
            78: "Acompañarte significa ayudarte a cumplir con cada requisito legal de forma simple y segura.",
            79: "Nuestro objetivo no es solo llenar formularios, sino construir historias que merecen ser escuchadas.",
            80: "Iniciar tu proceso hoy puede marcar la diferencia en tu futuro y el de tu familia."
        }
    },
    "PETICIÓN FAMILIAR": {
        "días": {
            1: "Hola 😊, qué gusto saludarte. ¿Cómo te sientes al pensar en reunirte con tu familia a través de una petición migratoria?",
            2: "¡Buenos días! Qué bonito saber que estás dando este paso. ¿Qué te motivó a iniciar la petición familiar?",
            3: "Hola, me alegra saludarte. ¿Qué familiar te gustaría solicitar primero?",
            4: "¡Hola! ¿Qué esperas lograr con este proceso de reunificación familiar?",
            5: "Hola 😊, ¿qué dudas tienes sobre los primeros pasos del trámite de petición familiar?",
            6: "¡Buenos días! ¿Qué te inspiró a buscar ayuda para reunir a tu familia?",
            7: "Hola, ¿qué parte del proceso te gustaría entender mejor para sentirte más seguro?",
            8: "¡Hola! ¿Qué esperas conseguir con el acompañamiento profesional durante este trámite?",
            9: "Hola, ¿qué te gustaría que tu familia supiera sobre este proceso que estás por iniciar?",
            10: "Hola, ¿qué te animaría a dar el primer paso en tu trámite familiar?"
        },
        "semana_1": {
            11: "Hola, ¿cómo te ha ido con la documentación para tu petición familiar?",
            12: "¡Buenos días ! ¿Qué parte del proceso te gustaría que te explique paso a paso?",
            13: "Hola, ¿qué preguntas te surgieron al revisar los requisitos de tu trámite?",
            14: "¡Hola! ¿Qué información te gustaría confirmar antes de enviar tu solicitud?",
            15: "Hola, ¿cómo te gustaría que te acompañemos durante esta etapa inicial?",
            16: "¡Buenos días ! ¿Qué parte del proceso te genera más curiosidad o inseguridad?",
            17: "Hola, ¿qué te gustaría saber sobre los tiempos de espera para tu tipo de caso?",
            18: "¡Hola! ¿Qué familiares piensas incluir en tu proceso?",
            19: "Hola, ¿qué paso te gustaría completar primero para avanzar con tu trámite?",
            20: "Hola, ¿qué día crees que podrías reunir los documentos básicos?"
        },
        "semana_2_3": {
            21: "Hola, ¿qué avances lograste desde la última vez con tu trámite familiar?",
            22: "¡Buenos días ! ¿Qué información te gustaría tener más clara sobre la petición de tu familiar?",
            23: "Hola, ¿qué parte del proceso te gustaría repasar antes de enviarlo?",
            24: "¡Hola! ¿Qué apoyo te gustaría recibir de nuestro equipo en esta fase?",
            25: "Hola, ¿cómo te sientes con los tiempos del trámite hasta ahora?",
            26: "¡Buenos días ! ¿Qué documentos te falta reunir para completar tu caso?",
            27: "Hola 😊, ¿qué te haría sentir más seguro para continuar este proceso?",
            28: "Hola, ¿qué dudas te gustaría aclarar antes de seguir avanzando?",
            29: "¡Hola! 😉, ¿Qué te gustaría lograr este mes con tu solicitud de petición familiar?",
            30: "Hola, ¿qué obstáculos sientes que te detienen y cómo puedo ayudarte a superarlos?"
        },
        "mes_1": {
            31: "Hola 😉, ¿cómo ha avanzado tu trámite familiar en las últimas semanas?",
            32: "¡Buenos días! ¿Qué parte del proceso te gustaría optimizar para avanzar más rápido?",
            33: "Hola, ¿qué familiares están involucrados y cómo te gustaría priorizarlos?",
            34: "Hola, ¿qué documentos crees que podrían fortalecer tu caso?",
            35: "Hola 😉, ¿cómo te sientes con el progreso de tu solicitud hasta ahora?",
            36: "¡Hola!, ¿Qué experiencia has tenido en los trámites anteriores y cómo podríamos mejorarla?",
            37: "Hola, ¿qué te gustaría revisar sobre las fechas y tiempos actuales del proceso?",
            38: "¡Buenos días! ¿Qué meta te gustaría lograr con tu caso familiar este mes?",
            39: "Hola 😉, ¿qué inquietudes te gustaría resolver para sentirte más tranquilo con el trámite?",
            40: "Hola, ¿qué tipo de seguimiento te haría sentir más acompañado?"
        },
        "mes_2_3": {
            41: "Hola, ha pasado un tiempo desde la última vez. ¿Qué novedades has tenido con tu caso familiar?",
            42: "¡Hola! ¿Qué resultado esperas obtener con tu trámite en los próximos meses?",
            43: "Hola, ¿cómo te has sentido con el avance de tu caso hasta el momento?",
            44: "¡Buenos días ! ¿Qué dudas tienes sobre el progreso de tu solicitud familiar?",
            45: "Hola, ¿qué apoyo crees que te ayudaría más en esta etapa?",
            46: "Hola, ¿cómo describirías tu experiencia con este proceso hasta hoy?",
            47: "¡Hola! ¿Qué paso crees que te falta para sentir que estás avanzando correctamente?",
            48: "Buenos días , ¿qué información te gustaría recibir sobre el estado actual de tu caso?",
            49: "Hola , ¿qué te motivó a iniciar tu trámite y qué te gustaría lograr a continuación?",
            50: "Hola , ¿qué parte del proceso consideras más importante reforzar?"
        },
        "mes_4_5": {
            51: "Hola , ¿cómo estás? ¿Qué te gustaría retomar del proceso de tu petición familiar?",
            52: "¡Buenos días ! ¿Qué novedades has tenido con tu caso o con tu familiar patrocinante?",
            53: "Hola , ¿qué parte del trámite crees que deberíamos revisar juntos para continuar?",
            54: "Hola , ¿qué cambios se han dado desde que comenzaste tu solicitud?",
            55: "¡Hola! ¿Qué paso te gustaría retomar primero esta semana?",
            56: "Buenos días , con solo $200 puedes retomar y actualizar tu trámite familiar fácilmente.",
            57: "Hola , ¿cómo te sientes con la posibilidad de reunirte pronto con tus seres queridos?",
            58: "¡Hola! ¿Qué te gustaría saber sobre las últimas actualizaciones del proceso familiar?",
            59: "Hola , ¿qué dudas te gustaría resolver antes de avanzar al siguiente paso?",
            60: "Buenos días , ¿cómo te gustaría que te acompañemos en esta etapa final del proceso?"
        },
        "valor": {
            61: "Sabías que iniciar tu petición familiar correctamente puede reducir hasta en meses los tiempos de espera 😊",
            62: "Nuestro equipo te guía en cada paso para que tu caso esté bien presentado desde el inicio.",
            63: "Una petición bien estructurada puede evitar rechazos y solicitudes adicionales de USCIS.",
            64: "Con el acompañamiento correcto, el proceso se vuelve más fácil y seguro.",
            65: "Muchos casos se retrasan por errores simples al llenar el formulario I-130; nosotros te ayudamos a evitarlo.",
            66: "Presentar evidencia sólida de la relación familiar aumenta las posibilidades de aprobación.",
            67: "Cada caso familiar es diferente; por eso brindamos asesoría personalizada según el tipo de vínculo.",
            68: "Nuestro equipo se asegura de que tus documentos estén completos antes del envío al USCIS.",
            69: "La transparencia y la comunicación constante son claves en tu trámite, y nosotros las priorizamos.",
            70: "Acompañarte en tu proceso familiar significa cuidar cada detalle con responsabilidad y empatía.",
            71: "Con solo $200 puedes comenzar tu trámite familiar con orientación profesional.",
            72: "Reunir a las familias es uno de los procesos más gratificantes que existen en inmigración.",
            73: "Una vez aprobada la petición, podrás continuar con el ajuste o consular sin contratiempos.",
            74: "Te ayudamos a entender los tiempos, categorías y pasos necesarios para tu tipo de relación.",
            75: "Cuando confías tu caso a profesionales, reduces el riesgo de errores que podrían costarte tiempo o dinero.",
            76: "Acompañarte en este proceso es garantizar que tu solicitud tenga respaldo legal y humano.",
            77: "Sabemos que cada historia familiar es única; tratamos tu caso con empatía y atención individual.",
            78: "Nuestro compromiso es ayudarte a reunir a tus seres queridos de forma segura y confiable.",
            79: "Las peticiones familiares bien preparadas son el primer paso hacia la estabilidad migratoria.",
            80: "Iniciar tu proceso familiar hoy puede acercarte antes a quienes más amas 😊"
        }
    },
    "PERMISO DE TRABAJO": {
        "días": {
            1: "Hola 😊, qué gusto saludarte. ¿Qué te motivó a iniciar el trámite para tu permiso de trabajo?",
            2: "¡Buenos días! ¿Qué te gustaría lograr al obtener tu permiso de trabajo?",
            3: "Hola, ¿cómo te sientes con el proceso para poder trabajar legalmente en Estados Unidos?",
            4: "¡Hola! ¿Qué parte del trámite te gustaría entender mejor antes de comenzar?",
            5: "Hola 😊, ¿qué te inspiró a buscar acompañamiento profesional para tu permiso?",
            6: "¡Buenos días! ¿Qué esperas conseguir cuando tengas tu permiso aprobado?",
            7: "Hola, ¿qué dudas te gustaría aclarar sobre los pasos para solicitarlo?",
            8: "¡Hola! ¿Qué parte del proceso te genera más incertidumbre o preocupación?",
            9: "Hola, ¿cómo te gustaría que te apoye en esta etapa inicial de tu solicitud?",
            10: "Hola, ¿qué tipo de trabajo esperas poder realizar una vez tengas tu permiso?"
        },
        "semana_1": {
            11: "Hola, ¿cómo te ha ido con la documentación de tu permiso de trabajo?",
            12: "¡Buenos días! ¿Qué parte del formulario te gustaría que revisemos juntos?",
            13: "Hola, ¿qué te gustaría saber sobre los tiempos de aprobación?",
            14: "¡Hola! ¿Qué información adicional necesitas para sentirte seguro al presentar tu solicitud?",
            15: "Hola, ¿cómo te gustaría que te acompañe durante esta primera fase del trámite?",
            16: "¡Buenos días! ¿Qué detalle te gustaría confirmar sobre la renovación o la primera solicitud?",
            17: "Hola, ¿qué obstáculos has tenido al intentar completar tu formulario?",
            18: "¡Hola! ¿Qué documentos crees que te hacen falta para iniciar?",
            19: "Hola, ¿qué experiencia te gustaría tener durante este proceso?",
            20: "Hola, ¿cómo te gustaría que sea tu seguimiento personalizado durante tu trámite?"
        },
        "semana_2_3": {
            21: "Hola, ¿cómo te ha ido con tu solicitud de permiso?",
            22: "¡Buenos días 😊! ¿Qué parte del proceso te gustaría repasar o actualizar?",
            23: "Hola 😊, ¿qué avances lograste desde la última vez que hablamos?",
            24: "¡Hola! ¿Qué información necesitas para continuar con seguridad?",
            25: "Hola 😉, ¿cómo te sientes con los plazos actuales de tu trámite?",
            26: "¡Buenos días 😊! ¿Qué te gustaría lograr este mes con tu proceso de permiso?",
            27: "Hola, ¿qué pasos consideras que te faltan para completar tu solicitud?",
            28: "Hola, ¿qué parte del proceso te gustaría revisar conmigo?",
            29: "¡Hola!️ ¿Qué te gustaría entender mejor sobre el seguimiento del caso?",
            30: "Hola, ¿qué te haría sentir más tranquilo con tu trámite de permiso de trabajo?"
        },
        "mes_1": {
            31: "Hola, ¿cómo ha evolucionado tu trámite desde la última vez?",
            32: "¡Buenos días 😊! ¿Qué te gustaría alcanzar en esta etapa de tu solicitud?",
            33: "Hola, ¿qué cambios has notado en tu proceso últimamente?",
            34: "Hola, ¿qué información adicional te gustaría tener sobre tu caso?",
            35: "Hola, ¿qué te haría sentir que estás avanzando de forma segura?",
            36: "¡Hola! ¿Qué resultados esperas obtener en los próximos días?",
            37: "Hola, ¿qué parte del formulario te resultó más difícil?",
            38: "¡Buenos días 😊! ¿Qué te gustaría optimizar en tu proceso actual?",
            39: "Hola, ¿qué aspecto crees que podríamos revisar para fortalecer tu solicitud?",
            40: "Hola, ¿qué te gustaría conversar hoy sobre tu trámite?"
        },
        "mes_2_3": {
            41: "Hola, ha pasado un tiempo desde la última vez. ¿Cómo va tu trámite de permiso?",
            42: "¡Hola! ¿Qué avances o novedades has tenido con tu caso?",
            43: "Hola, ¿cómo describirías tu experiencia con este proceso hasta ahora?",
            44: "¡Buenos días! ¿Qué información te gustaría que te actualice sobre tu permiso?",
            45: "Hola, ¿qué documentos crees que sería bueno revisar de nuevo?",
            46: "Hola, ¿cómo te has sentido con el avance o las demoras del proceso?",
            47: "¡Hola! ¿Qué paso te gustaría completar antes de que termine el mes?",
            48: "Buenos días, ¿qué meta te gustaría alcanzar con tu permiso de trabajo este trimestre?",
            49: "Hola, ¿qué parte del trámite te gustaría retomar conmigo?",
            50: "Hola, ¿qué información consideras más importante revisar ahora?"
        },
        "mes_4_5": {
            51: "Hola, ¿cómo has estado? ¿Qué te gustaría hacer con tu trámite de permiso en esta etapa?",
            52: "¡Buenos días! ¿Qué cambios has tenido en tu caso desde la última vez?",
            53: "Hola, ¿qué paso te gustaría retomar esta semana?",
            54: "Hola, ¿qué detalles quisieras actualizar antes de continuar con tu trámite?",
            55: "¡Hola! ¿Qué te inspiró a iniciar tu solicitud y qué te gustaría lograr ahora?",
            56: "Buenos días, recuerda que con solo $200 puedes avanzar con tu proceso de forma segura.",
            57: "Hola, ¿qué te motivaría a retomar tu trámite y completarlo este mes?",
            58: "¡Hola! 😊 Me alegra saludarte. ¿Qué te gustaría revisar para seguir avanzando?",
            59: "Hola 😊, ¿qué expectativas tienes ahora respecto a tu permiso de trabajo?",
            60: "Buenos días 😊, ¿cómo te gustaría que te acompañe en esta etapa final del proceso?"
        },
        "valor": {
            61: "Mantener tu permiso de trabajo vigente te permite acceder a más oportunidades y estabilidad.",
            62: "Si ya cuentas con un caso migratorio activo, tu permiso puede gestionarse más rápido de lo que imaginas.",
            63: "Un formulario bien presentado evita retrasos y solicitudes adicionales de USCIS.",
            64: "Con la orientación adecuada, puedes tramitar tu permiso con confianza y sin errores.",
            65: "Tener tu permiso al día te protege ante inspecciones laborales y brinda tranquilidad legal.",
            66: "Cada renovación es una oportunidad para actualizar tus datos y mantener tu estatus en orden.",
            67: "Al presentar tu solicitud correctamente, tu caso puede avanzar sin contratiempos.",
            68: "Nuestro equipo revisa cada detalle para asegurar que tu trámite cumpla los requisitos de USCIS.",
            69: "Saber cuándo y cómo renovar tu permiso evita lapsos que pueden afectar tu empleo.",
            70: "Con solo $200 puedes iniciar tu trámite con acompañamiento profesional paso a paso.",
            71: "Te ayudamos a entender cada parte del formulario para evitar rechazos o devoluciones.",
            72: "Si tu permiso se vence pronto, es importante comenzar la renovación con tiempo.",
            73: "Tener asesoría personalizada garantiza que tu solicitud esté completa desde el inicio.",
            74: "Muchos retrasos ocurren por pequeños errores; contar con ayuda profesional los previene.",
            75: "Renovar o solicitar tu permiso es más rápido con la guía de expertos que conocen el proceso.",
            76: "Al mantener tu documentación al día, demuestras compromiso y responsabilidad migratoria.",
            77: "Nuestro equipo te acompaña desde la preparación hasta la recepción de tu aprobación.",
            78: "Una gestión correcta del permiso puede facilitar futuros beneficios migratorios.",
            79: "Más que un documento, el permiso de trabajo representa tu oportunidad para avanzar con estabilidad.",
            80: "Iniciar tu trámite hoy puede acercarte un paso más a tus metas personales y profesionales 😊"
        }
    },
    "NATURALIZACIÓN": {
        "días": {
            1: "Hola 😊, qué gusto saludarte. ¿Qué te motivó a comenzar el proceso para convertirte en ciudadano americano?",
            2: "¡Buenos días 😊! Me alegra saber que estás dando este paso tan importante. ¿Qué significa para ti obtener la ciudadanía?",
            3: "Hola 😊, ¿qué parte del proceso de naturalización te gustaría entender mejor antes de empezar?",
            4: "¡Hola! 😊 ¿Qué esperas lograr para ti o tu familia al convertirte en ciudadano?",
            5: "Hola 😊, ¿qué te impulsó a dar este paso hacia la estabilidad definitiva en Estados Unidos?",
            6: "¡Buenos días 😊! ¿Qué dudas te gustaría aclarar sobre los requisitos de la ciudadanía?",
            7: "Hola , ¿cómo te sientes con la idea de presentar tu examen y entrevista de naturalización?",
            8: "¡Hola! ¿Qué te gustaría saber sobre el proceso de solicitud?",
            9: "Hola , ¿qué te motivó a buscar orientación profesional para este trámite?",
            10: "Hola , ¿qué te haría sentir más seguro al iniciar tu camino hacia la ciudadanía?"
        },
        "semana_1": {
            11: "Hola , ¿cómo te ha ido revisando los requisitos para tu solicitud de ciudadanía?",
            12: "¡Buenos días ! ¿Qué parte del proceso te gustaría repasar con más detalle?",
            13: "Hola , ¿qué información te gustaría confirmar antes de enviar tu aplicación?",
            14: "¡Hola! ¿Qué paso te gustaría completar esta semana en tu trámite de naturalización?",
            15: "Hola , ¿cómo te sientes con los formularios y los documentos necesarios?",
            16: "¡Buenos días ! ¿Qué temas del examen te gustaría comenzar a practicar primero?",
            17: "Hola , ¿qué obstáculos te has encontrado al preparar tu caso?",
            18: "¡Hola! ¿Qué información adicional te haría sentir listo para aplicar?",
            19: "Hola , ¿qué metas personales te impulsan a obtener la ciudadanía?",
            20: "Hola , ¿cómo te gustaría que te acompañemos durante este proceso?"
        },
        "semana_2_3": {
            21: "Hola , ¿cómo avanza tu solicitud de naturalización?",
            22: "¡Buenos días 😊! ¿Qué parte del examen te gustaría reforzar más?",
            23: "Hola, ¿qué avances lograste con tus documentos o tu formulario N-400?",
            24: "¡Hola!️ ¿Qué paso te gustaría revisar conmigo para asegurarte de que todo esté correcto?",
            25: "Hola, ¿cómo te has sentido al preparar los requisitos del proceso?",
            26: "¡Buenos días 😊! ¿Qué dudas te gustaría resolver antes de presentar tu solicitud?",
            27: "Hola, ¿qué cambios has notado desde que comenzaste tu trámite?",
            28: "Hola, ¿qué parte del proceso crees que podrías fortalecer con ayuda profesional?",
            29: "¡Hola!️ ¿Qué objetivo te gustaría cumplir con este trámite en los próximos meses?",
            30: "Hola, ¿qué paso consideras más importante completar pronto?"
        },
        "mes_1": {
            31: "Hola, ¿cómo ha sido tu experiencia con el trámite de ciudadanía hasta ahora?",
            32: "¡Buenos días 😊! ¿Qué parte te gustaría mejorar o actualizar en tu solicitud?",
            33: "Hola, ¿qué aprendizajes has tenido en este proceso de naturalización?",
            34: "Hola, ¿qué te gustaría repasar antes de enviar tu caso a USCIS?",
            35: "Hola, ¿cómo te sientes con los tiempos del proceso y la preparación del examen?",
            36: "¡Hola!️ ¿Qué pasos te gustaría completar este mes para seguir avanzando?",
            37: "Hola, ¿qué temas te gustaría reforzar para la entrevista de ciudadanía?",
            38: "¡Buenos días 😊! ¿Qué documentos pendientes te gustaría revisar conmigo?",
            39: "Hola, ¿qué parte del proceso te gustaría agilizar o aclarar hoy?",
            40: "Hola, ¿qué detalles consideras importantes revisar antes de continuar?"
        },
        "mes_2_3": {
            41: "Hola, ha pasado un tiempo desde la última vez. ¿Qué avances has tenido con tu caso de ciudadanía?",
            42: "¡Hola! ¿Qué metas personales te impulsan a continuar con tu trámite?",
            43: "Hola, ¿cómo describirías tu experiencia con este proceso hasta hoy?",
            44: "¡Buenos días! ¿Qué nuevos pasos te gustaría completar antes de la entrevista?",
            45: "Hola, ¿qué tipo de apoyo consideras más útil en esta etapa de tu trámite?",
            46: "Hola, ¿qué te ha resultado más fácil o más retador en tu preparación?",
            47: "¡Hola! ¿Qué objetivos te gustaría lograr antes de finalizar el mes con tu caso?",
            48: "Buenos días, ¿qué información te gustaría que te comparta sobre los tiempos actuales del proceso?",
            49: "Hola, ¿qué cambios personales te motivan a seguir adelante con este paso tan importante?",
            50: "Hola, ¿qué te haría sentir completamente listo para tu entrevista o juramento?"
        },
        "mes_4_5": {
            51: "Hola, ¿cómo has estado? ¿Qué parte de tu trámite de naturalización te gustaría retomar?",
            52: "¡Buenos días! ¿Qué novedades tienes con tu solicitud desde la última vez que hablamos?",
            53: "Hola, ¿qué paso te gustaría completar esta semana para acercarte a tu ciudadanía?",
            54: "Hola, ¿qué información te gustaría actualizar sobre tu caso?",
            55: "¡Hola! ¿Qué te inspiró a iniciar este camino y qué te gustaría lograr ahora?",
            56: "Buenos días, recuerda que con solo $200 puedes retomar tu trámite con orientación profesional.",
            57: "Hola, ¿cómo te sientes con la posibilidad de obtener tu ciudadanía pronto?",
            58: "¡Hola! Me alegra saludarte. ¿Qué te gustaría revisar para seguir avanzando con tu proceso?",
            59: "Hola , ¿qué expectativas tienes ahora con respecto a tu naturalización?",
            60: "Buenos días, ¿cómo te gustaría que te acompañe en esta recta final hacia la ciudadanía?"
        },
        "valor": {
            61: "Obtener tu ciudadanía te da acceso a derechos como votar y patrocinar familiares directamente.",
            62: "La naturalización es el paso final hacia la estabilidad migratoria plena en Estados Unidos.",
            63: "Al prepararte bien para el examen, aumentas tus posibilidades de aprobación en la entrevista.",
            64: "Nuestro equipo te ayuda a entender cada pregunta del formulario N-400 para evitar errores.",
            65: "Ser ciudadano te permite viajar con más libertad y acceder a beneficios exclusivos.",
            66: "Muchos residentes postergan la ciudadanía por temor al examen; nosotros te preparamos para que lo superes con confianza.",
            67: "Con solo $200 puedes comenzar tu trámite con acompañamiento profesional paso a paso.",
            68: "Te ayudamos a reunir los documentos que demuestran tu residencia continua y buen carácter moral.",
            69: "Acompañarte en este proceso significa asegurarnos de que estés listo para el examen y la entrevista.",
            70: "La naturalización no solo es un trámite, es la culminación de tu camino migratorio en Estados Unidos.",
            71: "Cada caso es único; por eso revisamos tu historial migratorio para evitar inconvenientes.",
            72: "Presentar tu solicitud correctamente desde el inicio evita retrasos y solicitudes de evidencia adicional.",
            73: "Obtener la ciudadanía te permite patrocinar a familiares de forma más rápida y directa.",
            74: "Nuestro equipo te guía en la preparación del examen cívico, de inglés y la entrevista personal.",
            75: "Iniciar tu trámite hoy puede acercarte a la tranquilidad de tener nacionalidad estadounidense.",
            76: "Te ayudamos a entender las exenciones o ajustes a los que podrías tener derecho según tu caso.",
            77: "Mantener tu residencia al día es clave para la elegibilidad; nosotros verificamos que cumplas los requisitos.",
            78: "La ciudadanía representa seguridad jurídica, participación cívica y nuevas oportunidades.",
            79: "Acompañarte en este proceso es ayudarte a cumplir un sueño que cambiará tu futuro y el de tu familia.",
            80: "Dar este paso hoy puede marcar un antes y un después en tu vida en Estados Unidos 😊"
        }
    },
    "RESIDENCIA": {
        "días": {
            1: "Hola 😊, qué gusto saludarte. ¿Qué te motivó a iniciar el trámite para obtener tu residencia permanente?",
            2: "¡Buenos días 😊! Me alegra saber que estás considerando este paso. ¿Qué esperas lograr con tu residencia?",
            3: "Hola 😊, ¿qué parte del proceso de residencia te gustaría entender mejor antes de comenzar?",
            4: "¡Hola! 😊 ¿Qué significa para ti y tu familia obtener la residencia permanente?",
            5: "Hola 😊, ¿cómo te sientes al dar este paso hacia la estabilidad migratoria?",
            6: "¡Buenos días 😊! ¿Qué dudas te gustaría aclarar sobre los requisitos de la residencia?",
            7: "Hola , ¿qué información te gustaría recibir sobre los diferentes caminos para obtener la residencia?",
            8: "¡Hola! ¿Qué tipo de apoyo crees que necesitas para iniciar este proceso?",
            9: "Hola , ¿qué te impulsó a buscar asesoría profesional para tu trámite de residencia?",
            10: "Hola , ¿cómo te gustaría que te acompañemos en este importante paso?"
        },
        "semana_1": {
            11: "Hola , ¿cómo te ha ido revisando los requisitos para tu residencia?",
            12: "¡Buenos días ! ¿Qué categoría de residencia crees que aplica mejor a tu caso?",
            13: "Hola , ¿qué documentos has reunido hasta ahora para tu solicitud?",
            14: "¡Hola! ¿Qué parte del proceso te genera más dudas o inquietudes?",
            15: "Hola , ¿cómo te sientes con los formularios y requisitos de elegibilidad?",
            16: "¡Buenos días ! ¿Qué información adicional te gustaría tener antes de enviar tu aplicación?",
            17: "Hola , ¿qué obstáculos has encontrado al preparar tu caso?",
            18: "¡Hola! ¿Qué paso te gustaría completar primero en tu trámite de residencia?",
            19: "Hola , ¿qué metas personales te motivan a obtener tu residencia permanente?",
            20: "Hola , ¿cómo te gustaría que nuestro equipo te apoye durante este proceso?"
        },
        "semana_2_3": {
            21: "Hola , ¿cómo avanza tu preparación para la residencia?",
            22: "¡Buenos días 😊! ¿Qué parte de la documentación te gustaría revisar conmigo?",
            23: "Hola , ¿qué avances lograste con tus formularios o documentos?",
            24: "¡Hola! 😊 ¿Qué información necesitas para sentirte seguro al presentar tu solicitud?",
            25: "Hola , ¿cómo te has sentido con los requisitos y plazos del proceso?",
            26: "¡Buenos días 😊! ¿Qué dudas te gustaría resolver antes de continuar?",
            27: "Hola , ¿qué cambios has notado en tu situación desde que comenzaste este trámite?",
            28: "Hola , ¿qué parte del proceso consideras más importante fortalecer con ayuda profesional?",
            29: "¡Hola! 😊 ¿Qué objetivo te gustaría alcanzar con tu residencia en los próximos meses?",
            30: "Hola , ¿qué paso te gustaría priorizar para avanzar con confianza?"
        },
        "mes_1": {
            31: "Hola , ¿cómo ha sido tu experiencia con el trámite de residencia hasta ahora?",
            32: "¡Buenos días 😊! ¿Qué aspecto te gustaría optimizar en tu solicitud?",
            33: "Hola , ¿qué has aprendido sobre el proceso de residencia en estas semanas?",
            34: "Hola , ¿qué documentos te gustaría verificar antes de enviar tu caso?",
            35: "Hola , ¿cómo te sientes con los tiempos de procesamiento y los próximos pasos?",
            36: "¡Hola! 😊 ¿Qué metas te gustaría cumplir este mes con tu trámite?",
            37: "Hola , ¿qué requisitos te parecen más complejos y te gustaría aclarar?",
            38: "¡Buenos días 😊! ¿Qué apoyo adicional crees que necesitas en esta etapa?",
            39: "Hola , ¿qué parte de tu caso te gustaría repasar para asegurar su solidez?",
            40: "Hola , ¿cómo te gustaría continuar con tu proceso de residencia?"
        },
        "mes_2_3": {
            41: "Hola , ha pasado un tiempo. ¿Qué novedades has tenido con tu trámite de residencia?",
            42: "¡Hola! 😊 ¿Qué esperas lograr una vez obtengas tu residencia permanente?",
            43: "Hola , ¿cómo describirías tu camino hacia la residencia hasta hoy?",
            44: "¡Buenos días 😊! ¿Qué información te gustaría actualizar sobre tu caso?",
            45: "Hola , ¿qué tipo de acompañamiento te sería más útil en esta fase?",
            46: "Hola , ¿qué te ha resultado más retador en la preparación de tu solicitud?",
            47: "¡Hola! 😊 ¿Qué paso te gustaría completar antes de que finalice este mes?",
            48: "Buenos días , ¿qué dudas te gustaría resolver sobre el seguimiento de tu caso?",
            49: "Hola , ¿qué te motiva a seguir adelante con este proceso migratorio?",
            50: "Hola , ¿qué información consideras clave para avanzar con seguridad?"
        },
        "mes_4_5": {
            51: "Hola , ¿cómo has estado? ¿Qué te gustaría retomar de tu trámite de residencia?",
            52: "¡Buenos días 😊! ¿Qué cambios ha habido en tu caso desde la última vez?",
            53: "Hola , ¿qué paso te gustaría dar esta semana para acercarte a tu residencia?",
            54: "Hola , ¿qué detalles de tu solicitud te gustaría actualizar o reforzar?",
            55: "¡Hola! 😊 ¿Qué te inspiró a iniciar este proceso y qué te gustaría lograr ahora?",
            56: "Buenos días , recuerda que con solo $200 puedes retomar tu trámite con orientación profesional.",
            57: "Hola , ¿cómo te sientes con la posibilidad de obtener tu residencia pronto?",
            58: "¡Hola! 😊 Me alegra saludarte. ¿Qué te gustaría revisar para continuar avanzando?",
            59: "Hola , ¿qué expectativas tienes ahora con respecto a tu proceso de residencia?",
            60: "Buenos días , ¿cómo te gustaría que te acompañemos en esta etapa importante?"
        },
        "valor": {
            61: "Obtener tu residencia permanente es un paso clave hacia la estabilidad migratoria en Estados Unidos.",
            62: "La residencia te permite trabajar legalmente, viajar con más flexibilidad y acceder a beneficios.",
            63: "Cada categoría de residencia tiene requisitos específicos; te ayudamos a identificar la que mejor se adapta a tu caso.",
            64: "Presentar una solicitud completa y bien documentada reduce significativamente los tiempos de procesamiento.",
            65: "Nuestro equipo revisa cada detalle de tu formulario para evitar errores que puedan retrasar tu caso.",
            66: "Contar con residencia permanente es el primer paso para eventualmente solicitar la ciudadanía estadounidense.",
            67: "Te guiamos en la preparación de la entrevista y en la reunión de evidencia para fortalecer tu caso.",
            68: "Muchos casos se retrasan por documentos incompletos; nosotros nos aseguramos de que todo esté en orden.",
            69: "Con solo $200 puedes iniciar tu trámite con acompañamiento profesional paso a paso.",
            70: "La residencia no solo te da estatus legal, también paz mental y oportunidades de crecimiento.",
            71: "Acompañarte en este proceso significa brindarte claridad y confianza en cada etapa.",
            72: "Te ayudamos a entender tus obligaciones como residente permanente para mantener tu estatus.",
            73: "Una residencia bien gestionada puede abrir puertas a beneficios para tu familia también.",
            74: "Nuestro objetivo es que tu transición hacia la residencia sea smooth y sin contratiempos.",
            75: "Iniciar tu trámite hoy puede acercarte a la tranquilidad de tener tu estatus migratorio regularizado.",
            76: "Cada caso es tratado con atención personalizada, reconociendo la singularidad de tu situación.",
            77: "La residencia permanente representa seguridad, estabilidad y nuevas oportunidades en Estados Unidos.",
            78: "Te apoyamos desde la evaluación inicial hasta la entrega de tu green card.",
            79: "Este proceso no solo cambia tu estatus migratorio, puede transformar tu calidad de vida y futuro.",
            80: "Dar este paso con acompañamiento profesional te asegura un proceso más seguro y eficiente 😊"
        }
    },
    "CORTE": {
        "días": {
            1: "Hola 😊, qué gusto saludarte. ¿Cómo te sientes al tener que enfrentar un proceso en corte migratoria?",
            2: "¡Buenos días 😊! Sé que este puede ser un momento difícil. ¿Qué te gustaría entender mejor sobre tu caso?",
            3: "Hola 😊, ¿qué parte del proceso de corte te genera más preocupación o dudas?",
            4: "¡Hola! 😊 ¿Qué esperas lograr con una defensa adecuada en tu caso migratorio?",
            5: "Hola 😊, ¿cómo te ha impactado tener que presentarte ante la corte?",
            6: "¡Buenos días 😊! ¿Qué información te gustaría recibir sobre los pasos a seguir en corte?",
            7: "Hola , ¿qué tipo de apoyo crees que necesitas para enfrentar este proceso con más seguridad?",
            8: "¡Hola! ¿Qué te motivó a buscar asesoría profesional para tu caso en corte?",
            9: "Hola , ¿cómo te gustaría que te acompañemos durante este proceso legal?",
            10: "Hola , ¿qué pregunta te gustaría hacer sobre tu situación en corte?"
        },
        "semana_1": {
            11: "Hola , ¿cómo te ha ido con la preparación de tu caso para la corte?",
            12: "¡Buenos días ! ¿Qué documentación has reunido hasta ahora para tu defensa?",
            13: "Hola , ¿qué aspectos de tu caso te gustaría reforzar con evidencia adicional?",
            14: "¡Hola! ¿Qué dudas tienes sobre los próximos pasos en el proceso de corte?",
            15: "Hola , ¿cómo te sientes con los plazos y fechas de tu caso?",
            16: "¡Buenos días ! ¿Qué información te gustaría confirmar sobre tu elegibilidad para alivios migratorios?",
            17: "Hola , ¿qué obstáculos has encontrado al preparar tu defensa?",
            18: "¡Hola! ¿Qué tipo de alivio migratorio crees que podría aplicar a tu situación?",
            19: "Hola , ¿qué metas te gustaría alcanzar con una representación legal adecuada?",
            20: "Hola , ¿cómo te gustaría que nuestro equipo te apoye en este proceso?"
        },
        "semana_2_3": {
            21: "Hola , ¿cómo avanza la preparación de tu caso para corte?",
            22: "¡Buenos días 😊! ¿Qué parte de tu defensa te gustaría fortalecer?",
            23: "Hola , ¿qué avances has logrado en reunir evidencia para tu caso?",
            24: "¡Hola! 😊 ¿Qué información necesitas para sentirte más preparado para tu próxima audiencia?",
            25: "Hola , ¿cómo te has sentido con el desarrollo de tu caso hasta ahora?",
            26: "¡Buenos días 😊! ¿Qué dudas te gustaría resolver sobre el proceso judicial?",
            27: "Hola , ¿qué cambios has notado en tu situación desde que comenzaste a preparar tu defensa?",
            28: "Hola , ¿qué aspecto de tu caso consideras más importante trabajar con un abogado?",
            29: "¡Hola! 😊 ¿Qué objetivo te gustaría lograr con tu caso en los próximos meses?",
            30: "Hola , ¿qué paso te gustaría priorizar en tu estrategia de defensa?"
        },
        "mes_1": {
            31: "Hola , ¿cómo ha evolucionado tu caso en corte desde que comenzamos a trabajar juntos?",
            32: "¡Buenos días 😊! ¿Qué aspecto de tu defensa te gustaría optimizar?",
            33: "Hola , ¿qué has aprendido sobre el proceso de corte migratoria en este tiempo?",
            34: "Hola , ¿qué evidencia te gustaría recolectar adicionalmente para fortalecer tu caso?",
            35: "Hola , ¿cómo te sientes con los avances o retrocesos en tu proceso?",
            36: "¡Hola! 😊 ¿Qué metas te gustaría cumplir este mes con tu caso?",
            37: "Hola , ¿qué argumentos de defensa te gustaría desarrollar mejor?",
            38: "¡Buenos días 😊! ¿Qué apoyo adicional crees que necesitas en esta etapa?",
            39: "Hola , ¿qué parte de tu estrategia legal te gustaría ajustar?",
            40: "Hola , ¿cómo te gustaría continuar con la preparación de tu defensa?"
        },
        "mes_2_3": {
            41: "Hola , ha pasado un tiempo. ¿Qué novedades has tenido con tu caso en corte?",
            42: "¡Hola! 😊 ¿Qué esperas lograr con una resolución favorable en tu caso?",
            43: "Hola , ¿cómo describirías tu experiencia con el sistema de corte migratoria?",
            44: "¡Buenos días 😊! ¿Qué información te gustaría actualizar sobre tu situación legal?",
            45: "Hola , ¿qué tipo de representación te sería más útil en esta fase del proceso?",
            46: "Hola , ¿qué te ha resultado más desafiante en la defensa de tu caso?",
            47: "¡Hola! 😊 ¿Qué paso te gustaría completar antes de tu próxima audiencia?",
            48: "Buenos días , ¿qué dudas te gustaría resolver sobre las opciones legales disponibles?",
            49: "Hola , ¿qué te motiva a continuar luchando por tu caso migratorio?",
            50: "Hola , ¿qué información consideras crucial para el éxito de tu defensa?"
        },
        "mes_4_5": {
            51: "Hola , ¿cómo has estado? ¿Qué te gustaría retomar de tu caso en corte?",
            52: "¡Buenos días 😊! ¿Qué cambios ha habido en tu situación legal recientemente?",
            53: "Hola , ¿qué paso te gustría dar esta semana para avanzar con tu defensa?",
            54: "Hola , ¿qué aspectos de tu caso te gustaría revisar o actualizar?",
            55: "¡Hola! 😊 ¿Qué te inspiró a buscar representación legal y qué esperas lograr ahora?",
            56: "Buenos días , recuerda que con solo $200 puedes obtener asesoría inicial para tu caso en corte.",
            57: "Hola , ¿cómo te sientes con la posibilidad de obtener un resultado favorable?",
            58: "¡Hola! 😊 Me alegra saludarte. ¿Qué te gustaría revisar para fortalecer tu posición legal?",
            59: "Hola , ¿qué expectativas tienes ahora con respecto al desenlace de tu caso?",
            60: "Buenos días , ¿cómo te gustaría que te acompañemos en este proceso judicial?"
        },
        "valor": {
            61: "Contar con representación legal en corte migratoria puede aumentar significativamente tus posibilidades de éxito.",
            62: "Cada caso en corte es único; te ayudamos a identificar la mejor estrategia de defensa para tu situación específica.",
            63: "Preparar una defensa sólida con evidencia contundente es crucial para obtener un resultado favorable.",
            64: "Nuestro equipo te guía en la comprensión de tus derechos y opciones durante el proceso judicial.",
            65: "Mantener una comunicación constante con tu abogado puede marcar la diferencia en el resultado de tu caso.",
            66: "Te ayudamos a entender los diferentes tipos de alivio migratorio para los que podrías ser elegible.",
            67: "Presentar argumentos legales bien fundamentados es esencial para persuadir al juez de inmigración.",
            68: "La preparación meticulosa de testimonios y documentación fortalece tu posición ante la corte.",
            69: "Con solo $200 puedes obtener una evaluación inicial de tu caso y plan de acción.",
            70: "Acompañarte en este proceso significa brindarte claridad y apoyo durante un momento difícil.",
            71: "Te asistimos en la preparación para audiencias y en la presentación de mociones cuando sea necesario.",
            72: "Entender el procedimiento de corte te ayuda a enfrentar el proceso con mayor confianza y tranquilidad.",
            73: "Cada detalle de tu historia personal puede ser relevante; te ayudamos a identificar qué información incluir.",
            74: "La consistencia en tu testimonio y documentación es clave para construir credibilidad ante el juez.",
            75: "Iniciar tu defensa a tiempo puede permitirte explorar más opciones legales y preparar mejor tu caso.",
            76: "Nuestro objetivo es garantizar que tu voz sea escuchada y tu situación comprendida en su totalidad.",
            77: "La representación legal adecuada puede ayudarte a navegar el complejo sistema de corte migratoria.",
            78: "Te apoyamos desde la evaluación inicial hasta la representación en audiencias y apelaciones si es necesario.",
            79: "Este proceso no solo define tu estatus migratorio, puede determinar tu futuro y el de tu familia.",
            80: "Confiar en profesionales con experiencia en corte migratoria te da la mejor oportunidad para regularizar tu situación 😊"
        }
    },
    "CAMBIO DE DIRECCIÓN": {
        "días": {
            1: "Hola 😊, qué gusto saludarte. ¿Qué te motivó a actualizar tu dirección con inmigración?",
            2: "¡Buenos días! Me alegra saber de ti. ¿Hace cuánto realizaste tu mudanza?",
            3: "Hola, ¿qué te llevó a buscar apoyo para hacer tu cambio de dirección correctamente?",
            4: "¡Hola! ¿Qué te gustaría entender mejor del proceso de actualización ante USCIS?",
            5: "Hola, ¿qué te preocupa más al hacer tu cambio de domicilio?",
            6: "¡Buenos días! ¿Qué tipo de casos tienes activos que requieren actualizar dirección?",
            7: "Hola, ¿qué información te gustaría confirmar antes de presentar tu formulario?",
            8: "¡Hola! ¿Qué te impulsó a hacerlo ahora y no esperar más tiempo?",
            9: "Hola, ¿cómo te gustaría que te acompañe en este trámite para evitar errores?",
            10: "Hola, ¿qué experiencia tuviste en trámites anteriores con USCIS?"
        },
        "semana_1": {
            11: "Hola, ¿cómo te ha ido con tu actualización de dirección hasta ahora?",
            12: "¡Buenos días! ¿Qué parte del formulario AR-11 te ha generado dudas?",
            13: "Hola, ¿qué documentos tienes listos para confirmar tu nueva dirección?",
            14: "¡Hola! ¿Qué información necesitas para asegurarte de que tu cambio quede registrado correctamente?",
            15: "Hola, ¿cómo te gustaría que te apoye durante este proceso de actualización?",
            16: "¡Buenos días! ¿Qué pasos crees que te faltan para completar tu trámite?",
            17: "Hola, ¿qué te ha parecido más fácil o más confuso del cambio de dirección?",
            18: "¡Hola! ¿Qué te gustaría saber sobre los plazos en que USCIS actualiza tu información?",
            19: "Hola, ¿cómo te gustaría mantener tus casos actualizados para no perder notificaciones importantes?",
            20: "Hola 😊, ¿qué día te gustaría que revisemos tu formulario juntos?"
        },
        "semana_2_3": {
            21: "Hola, ¿cómo avanza tu cambio de dirección?",
            22: "¡Buenos días! ¿Qué parte del proceso te gustaría revisar otra vez?",
            23: "Hola, ¿qué avances lograste desde la última vez que hablamos?",
            24: "¡Hola! ¿Qué te gustaría verificar para asegurarte de que tu dirección esté correcta?",
            25: "Hola 😉, ¿qué dudas te surgieron al revisar la confirmación de USCIS?",
            26: "¡Buenos días! ¿Qué te gustaría lograr esta semana con tu trámite de cambio de domicilio?",
            27: "Hola, ¿cómo te has sentido con el proceso hasta ahora?",
            28: "Hola, ¿qué te gustaría reforzar para tener tranquilidad con tu caso?",
            29: "¡Hola! ¿Qué te gustaría entender mejor sobre la actualización en tus diferentes formularios?",
            30: "Hola, ¿qué cambios se dieron en tu situación que motivaron este trámite?"
        },
        "mes_1": {
            31: "Hola, ¿cómo ha sido tu experiencia con el cambio de dirección hasta este punto?",
            32: "¡Buenos días! ¿Qué detalles te gustaría revisar para confirmar que todo esté en orden?",
            33: "Hola, ¿qué aprendiste del proceso hasta ahora?",
            34: "Hola, ¿qué otros trámites te gustaría actualizar junto con este?",
            35: "Hola 😊, ¿cómo te sientes con la información que ya registraste ante USCIS?",
            36: "¡Hola! ¿Qué pasos te gustaría completar este mes para cerrar tu trámite?",
            37: "Hola, ¿qué parte te gustaría repasar para asegurarte de que no haya errores?",
            38: "¡Buenos días! ¿Qué te gustaría lograr en esta etapa con tu proceso migratorio?",
            39: "Hola 😊, ¿qué información consideras importante mantener actualizada en tus formularios?",
            40: "Hola, ¿qué parte del proceso te gustaría hacer más sencilla?"
        },
        "mes_2_3": {
            41: "Hola, ha pasado un tiempo desde la última vez. ¿Qué avances tuviste con tu cambio de dirección?",
            42: "¡Hola! ¿Qué resultados esperas obtener al mantener tu información actualizada?",
            43: "Hola 😊, ¿cómo describirías tu experiencia con este trámite hasta ahora?",
            44: "¡Buenos días! ¿Qué documentos te gustaría volver a revisar para confirmar tu domicilio?",
            45: "Hola, ¿qué parte del proceso te gustaría reforzar o actualizar?",
            46: "Hola, ¿qué te ha resultado más sencillo o más difícil durante este trámite?",
            47: "¡Hola! 😊 ¿Qué expectativas tienes sobre la confirmación final del cambio de dirección?",
            48: "Buenos días, ¿qué dudas te gustaría resolver antes de continuar con otros procesos?",
            49: "Hola, ¿qué te motivó a mantener todo tu expediente migratorio al día?",
            50: "Hola, ¿qué información consideras esencial para mantener la comunicación con USCIS?"
        },
        "mes_4_5": {
            51: "Hola, ¿cómo has estado? ¿Qué parte del trámite te gustaría retomar?",
            52: "¡Buenos días! ¿Qué novedades has tenido con tu caso o dirección desde la última vez?",
            53: "Hola, ¿qué pasos te gustaría dar para confirmar tu dirección actual ante inmigración?",
            54: "Hola, ¿qué actualizaciones te gustaría realizar en tus demás formularios?",
            55: "¡Hola! ¿Qué te impulsó a mantener todo en regla con USCIS?",
            56: "Buenos días, con solo $200 puedes realizar este trámite de forma rápida y segura.",
            57: "Hola, ¿qué te motiva a seguir manteniendo tu información al día?",
            58: "¡Hola! Me alegra saludarte. ¿Qué información adicional te gustaría recibir para continuar?",
            59: "Hola, ¿qué te gustaría revisar para garantizar que tus casos sigan activos correctamente?",
            60: "Buenos días, ¿cómo te gustaría que te apoyemos para finalizar tu actualización?"
        },
        "valor": {
            61: "Mantener tu dirección actualizada evita que pierdas notificaciones importantes de USCIS.",
            62: "Con una actualización correcta, garantizas que toda tu correspondencia llegue a tiempo.",
            63: "Este trámite puede hacerse en minutos con el acompañamiento adecuado.",
            64: "Con solo $200 puedes actualizar tu dirección y dejar tu expediente en orden.",
            65: "Un cambio de dirección mal notificado puede causar retrasos o cierres de caso.",
            66: "Nuestro equipo revisa que cada actualización se aplique correctamente a todos tus formularios.",
            67: "Evitar errores en este trámite te ahorra tiempo y posibles complicaciones futuras.",
            68: "USCIS requiere que todo inmigrante notifique cambios de domicilio en menos de 10 días.",
            69: "Actualizar tu dirección demuestra responsabilidad y compromiso con tu estatus migratorio.",
            70: "Con ayuda profesional, puedes hacerlo una sola vez y asegurar que quede bien registrado.",
            71: "Revisamos tu número de caso y vinculamos tu nueva dirección a todos tus trámites activos.",
            72: "Mantener tu dirección actualizada también protege tu derecho a recibir decisiones oficiales.",
            73: "Te ayudamos a confirmar que tu nueva dirección aparezca en todos los sistemas de USCIS.",
            74: "Este trámite sencillo puede evitarte pérdidas de tiempo o solicitudes de evidencia innecesarias.",
            75: "Nuestro acompañamiento garantiza que cada detalle se procese correctamente.",
            76: "Una dirección correcta puede marcar la diferencia entre recibir tu notificación o perderla.",
            77: "Acompañarte en este trámite es nuestra forma de garantizar tu tranquilidad migratoria.",
            78: "Cada actualización correcta fortalece la credibilidad de tu historial ante USCIS.",
            79: "Te ayudamos a hacerlo una sola vez, de forma segura y sin errores.",
            80: "Mantener tu dirección al día es una acción pequeña, pero con un gran impacto en tu caso 😊"
        }
    },
    "FEE ANUAL DE ASILO": {
        "días": {
            1: "Hola, qué gusto saludarte. ¿Hace cuánto presentaste tu solicitud de asilo?",
            2: "¡Buenos días! Me alegra saludarte. ¿Qué te llevó a consultar sobre el fee anual de asilo?",
            3: "Hola, ¿qué información te gustaría tener más clara sobre este pago obligatorio?",
            4: "¡Hola! ¿Qué dudas tienes sobre cuándo o cómo se debe pagar el fee anual?",
            5: "Hola, ¿qué te preocupa más sobre el proceso del fee anual?",
            6: "¡Buenos días! ¿Qué te gustaría entender mejor sobre cómo mantener tu caso activo?",
            7: "Hola, ¿ya recibiste la notificación de tu fee anual o quieres que te ayude a confirmarlo?",
            8: "¡Hola! ¿Qué parte del proceso te genera más confusión?",
            9: "Hola, ¿qué paso te gustaría revisar antes de hacer tu pago?",
            10: "Hola, ¿cómo te gustaría que te acompañemos para hacerlo correctamente?"
        },
        "semana_1": {
            11: "Hola, ¿cómo te ha ido revisando tu carta del fee anual?",
            12: "¡Buenos días! ¿Qué parte del pago te gustaría que te explique paso a paso?",
            13: "Hola, ¿qué dudas tienes sobre los plazos para hacer tu pago este año?",
            14: "¡Hola! ¿Qué información te gustaría confirmar antes de enviar tu comprobante?",
            15: "Hola, ¿cómo te gustaría que te ayudemos a asegurarte de que el pago quede registrado?",
            16: "¡Buenos días! ¿Qué pasos crees que te faltan para completar tu trámite del fee anual?",
            17: "Hola, ¿qué te ha parecido más fácil o más complicado del proceso hasta ahora?",
            18: "¡Hola! ¿Qué tipo de ayuda consideras más útil en este momento?",
            19: "Hola, ¿qué fecha estimas que podrías realizar tu pago?",
            20: "Hola, ¿qué forma de acompañamiento prefieres: revisión previa o confirmación del pago?"
        },
        "semana_2_3": {
            21: "Hola, ¿cómo avanza tu trámite del fee anual?",
            22: "¡Buenos días! ¿Qué te gustaría revisar esta semana para asegurarte de que todo esté al día?",
            23: "Hola, ¿qué avances lograste desde la última vez con tu pago anual?",
            24: "¡Hola! ¿Qué información adicional te haría sentir más tranquilo antes de hacer el pago?",
            25: "Hola, ¿qué parte del proceso te gustaría repasar para no tener errores?",
            26: "¡Buenos días! ¿Qué dudas te gustaría resolver sobre la confirmación de tu pago?",
            27: "Hola, ¿qué documentos o cartas recibiste recientemente de USCIS sobre tu caso?",
            28: "Hola 🟿, ¿qué paso te gustaría completar para mantener tu caso de asilo activo?",
            29: "¡Hola! 🟹 ¿Qué te gustaría entender mejor sobre la relación entre tu fee anual y tu carta de reloj?",
            30: "Hola, ¿qué apoyo te ayudaría a realizar tu pago sin preocupaciones?"
        },
        "mes_1": {
            31: "Hola 😊, ¿cómo ha sido tu experiencia con el trámite del fee anual hasta ahora?",
            32: "¡Buenos días! ¿Qué detalles te gustaría revisar antes de enviar tu comprobante?",
            33: "Hola, ¿qué cambios has notado desde que comenzaste este trámite?",
            34: "Hola, ¿qué información consideras clave para no tener retrasos con USCIS?",
            35: "Hola, ¿cómo te sientes con los plazos del fee anual?",
            36: "¡Hola! ¿Qué te gustaría lograr esta semana con tu proceso de actualización?",
            37: "Hola, ¿qué parte te gustaría reforzar o verificar de tu caso?",
            38: "¡Buenos días! ¿Qué pasos te gustaría completar este mes?",
            39: "Hola, ¿qué información te gustaría tener para sentirte seguro de que tu caso sigue activo?",
            40: "Hola, ¿qué aspecto de tu fee anual te gustaría aclarar hoy?"
        },
        "mes_2_3": {
            41: "Hola, ha pasado un tiempo desde la última vez. ¿Cómo va tu trámite del fee anual?",
            42: "¡Hola! ¿Qué avances tuviste o qué te gustaría retomar esta semana?",
            43: "Hola, ¿cómo describirías tu experiencia con este proceso hasta ahora?",
            44: "¡Buenos días! ¿Qué dudas tienes sobre la confirmación o el registro del pago?",
            45: "Hola, ¿qué parte del proceso te gustaría reforzar antes de la próxima fecha límite?",
            46: "Hola, ¿qué te ha resultado más fácil o más desafiante durante el trámite?",
            47: "¡Hola! ¿Qué paso te gustaría completar este mes para mantener tu caso activo?",
            48: "Buenos días, ¿qué información te gustaría que te actualice sobre los pagos anuales?",
            49: "Hola 😊, ¿qué aspectos te gustaría revisar para asegurarte de que tu expediente esté completo?",
            50: "Hola, ¿qué meta tienes para cerrar tu trámite de fee anual con éxito?"
        },
        "mes_4_5": {
            51: "Hola, ¿cómo has estado? ¿Qué parte del trámite te gustaría retomar?",
            52: "¡Buenos días! ¿Qué novedades has tenido con tu fee anual desde la última vez?",
            53: "Hola, ¿qué te gustaría lograr esta semana con tu caso de asilo?",
            54: "Hola, ¿qué información te gustaría confirmar sobre tus pagos anteriores?",
            55: "¡Hola! ¿Qué te impulsó a mantener tu caso activo con responsabilidad?",
            56: "Buenos días, recuerda que con solo $200 puedes ponerte al día con tu fee anual de forma segura.",
            57: "Hola, ¿qué te motiva a mantener tu estatus de asilo en regla cada año?",
            58: "¡Hola! Me alegra saludarte. ¿Qué apoyo adicional te gustaría recibir para completar tu trámite?",
            59: "Hola, ¿qué pasos consideras más importantes para evitar retrasos o errores?",
            60: "Buenos días, ¿cómo te gustaría que te apoyemos para finalizar este proceso de forma correcta?"
        },
        "valor": {
            61: "El fee anual mantiene tu solicitud de asilo activa y demuestra tu compromiso con el proceso.",
            62: "Hacer este pago a tiempo evita que tu caso sea archivado o suspendido por USCIS.",
            63: "Nuestro equipo te guía paso a paso para que tu pago quede correctamente registrado.",
            64: "Con solo $200 puedes recibir asistencia completa para actualizar tu fee anual de forma segura.",
            65: "Presentar tu comprobante correctamente te da tranquilidad y respaldo legal.",
            66: "Cada año, USCIS solicita este pago como parte del seguimiento de tu caso de asilo.",
            67: "Si no has recibido tu notificación, podemos ayudarte a confirmar tu fecha exacta.",
            68: "Mantener tu fee anual al día demuestra que tu caso sigue activo y en buen estado.",
            69: "Nuestro equipo revisa tu expediente para asegurar que el pago se vincule correctamente a tu número de caso.",
            70: "Un simple error en la referencia del pago puede retrasar la actualización de tu estatus.",
            71: "Te ayudamos a realizar el trámite sin estrés y con toda la documentación necesaria.",
            72: "Cumplir con tu fee anual te mantiene protegido y evita complicaciones futuras.",
            73: "Este proceso puede completarse fácilmente con acompañamiento profesional.",
            74: "La actualización anual es un requisito esencial para conservar tu derecho al asilo.",
            75: "Con una correcta gestión, tu fee anual quedará registrado sin demoras.",
            76: "Nuestra asistencia asegura que tu pago cumpla con todos los criterios exigidos por USCIS.",
            77: "Al mantener tu fee anual al día, garantizas la continuidad de tu caso sin interrupciones.",
            78: "Nuestro compromiso es ayudarte a mantener tu estatus migratorio estable y protegido.",
            79: "Con asesoría profesional, este trámite se hace en minutos y sin riesgos de error.",
            80: "Estar al día con tu fee anual es un paso pequeño, pero fundamental para tu tranquilidad 😊"
        }
    },
    "CARTA DE RELOJ": {
        "días": {
            1: "Hola 😊, qué gusto saludarte. ¿Cómo te ha ido con tu caso de asilo hasta ahora?",
            2: "¡Buenos días! ¿Has escuchado hablar de la carta de reloj y cómo puede ayudarte con tu permiso de trabajo?",
            3: "Hola, ¿qué te motivó a consultar sobre la carta de reloj?",
            4: "¡Hola! ¿Qué te gustaría entender mejor sobre cómo funciona el reloj de tu caso de asilo?",
            5: "Hola 😊, ¿qué dudas tienes sobre los días acumulados del reloj?",
            6: "¡Buenos días! ¿Qué parte del proceso te gustaría revisar para confirmar si tu reloj está activo?",
            7: "Hola, ¿ya sabes cuántos días tiene tu reloj de asilo o quieres que te ayude a calcularlos?",
            8: "¡Hola! ¿Qué te gustaría revisar primero: tu carta o el estatus de tu reloj?",
            9: "Hola, ¿qué te preocupa más: el conteo de días o la carta que aún no recibes?",
            10: "Hola 😊, ¿cómo te gustaría que te acompañemos para revisar tu carta de reloj?"
        },
        "semana_1": {
            11: "Hola 😊, ¿cómo te ha ido con la revisión de tu carta de reloj?",
            12: "¡Buenos días! ¿Qué parte del proceso te gustaría aclarar conmigo?",
            13: "Hola, ¿qué información has recibido sobre tu reloj desde la última vez?",
            14: "¡Hola! ¿Qué paso crees que te falta para solicitar tu carta?",
            15: "Hola, ¿qué dudas te surgieron al revisar el estatus de tu reloj?",
            16: "¡Buenos días! ¿Qué te gustaría lograr esta semana con tu trámite de carta de reloj?",
            17: "Hola, ¿qué parte del proceso te resulta más confusa hasta ahora?",
            18: "¡Hola! ¿Qué fecha estimas que podrías solicitar tu carta?",
            19: "Hola, ¿cómo te gustaría que te apoyemos para verificar si tu reloj está activo?",
            20: "Hola, ¿qué meta te gustaría alcanzar este mes con tu caso?"
        },
        "semana_2_3": {
            21: "Hola, ¿cómo avanza tu trámite de carta de reloj?",
            22: "¡Buenos días! ¿Qué avances lograste desde la última vez?",
            23: "Hola, ¿qué parte del proceso te gustaría repasar juntos?",
            24: "¡Hola! ¿Qué información te gustaría tener sobre la relación entre tu reloj y el permiso de trabajo?",
            25: "Hola, ¿qué dudas tienes sobre los días que han sido contados en tu caso?",
            26: "¡Buenos días! ¿Qué paso te gustaría completar antes de enviar tu solicitud?",
            27: "Hola, ¿qué te ha resultado más fácil o más retador en este trámite?",
            28: "Hola, ¿qué te gustaría reforzar o confirmar antes de avanzar?",
            29: "¡Hola! ¿Qué apoyo te ayudaría a sentirte más seguro en esta etapa?",
            30: "Hola, ¿qué paso crees que te acerca más a tu permiso de trabajo?"
        },
        "mes_1": {
            31: "Hola, ¿cómo ha sido tu experiencia con la carta de reloj hasta ahora?",
            32: "¡Buenos días! ¿Qué detalles te gustaría revisar para confirmar si tu reloj está corriendo?",
            33: "Hola, ¿qué documentos has recibido recientemente de USCIS sobre tu caso?",
            34: "Hola, ¿qué parte te gustaría entender mejor sobre los días de conteo?",
            35: "Hola, ¿qué información consideras más importante revisar en tu carta?",
            36: "¡Hola! ¿Qué te gustaría lograr este mes con tu trámite?",
            37: "Hola, ¿qué parte del proceso quieres revisar conmigo para asegurarte de que todo esté correcto?",
            38: "¡Buenos días! ¿Qué dudas tienes sobre el tiempo que falta para tu permiso de trabajo?",
            39: "Hola, ¿qué resultados esperas obtener al revisar tu carta de reloj?",
            40: "Hola, ¿qué aspecto te gustaría aclarar hoy sobre tu reloj de asilo?"
        },
        "mes_2_3": {
            41: "Hola, ha pasado un tiempo desde la última vez. ¿Cómo va tu proceso de carta de reloj?",
            42: "¡Hola! ¿Qué avances tuviste o qué te gustaría retomar esta semana?",
            43: "Hola, ¿cómo describirías tu experiencia con este trámite hasta ahora?",
            44: "¡Buenos días! ¿Qué dudas te gustaría resolver sobre el conteo de tus días?",
            45: "Hola, ¿qué te gustaría confirmar sobre la relación entre tu asilo y la carta de reloj?",
            46: "Hola, ¿qué cambios has notado en el estatus de tu caso últimamente?",
            47: "¡Hola! 😊 ¿Qué paso te gustaría completar para acercarte más a tu permiso de trabajo?",
            48: "Buenos días, ¿qué información te gustaría que te comparta sobre los tiempos de espera?",
            49: "Hola, ¿qué parte de tu proceso de asilo te gustaría revisar junto con tu reloj?",
            50: "Hola, ¿qué meta tienes para cerrar tu trámite de carta de reloj con éxito?"
        },
        "mes_4_5": {
            51: "Hola, ¿cómo has estado? ¿Qué parte del proceso te gustaría retomar?",
            52: "¡Buenos días! ¿Qué novedades has tenido con tu carta o tu caso desde la última vez?",
            53: "Hola, ¿qué te gustaría lograr esta semana en tu trámite de carta de reloj?",
            54: "Hola, ¿qué información quisieras confirmar sobre el conteo de tus días?",
            55: "¡Hola! ¿Qué te motivó a mantener tu caso de asilo al día?",
            56: "Buenos días, con solo $200 puedes recibir ayuda para revisar tu carta y tu tiempo acumulado.",
            57: "Hola, ¿qué te motiva a continuar avanzando con tu caso?",
            58: "¡Hola! Me alegra saludarte. ¿Qué apoyo adicional te gustaría recibir para avanzar con tu reloj?",
            59: "Hola, ¿qué parte del trámite te gustaría aclarar antes de continuar con tu permiso?",
            60: "Buenos días, ¿cómo te gustaría que te acompañemos en esta etapa final?"
        },
        "valor": {
            61: "La carta de reloj muestra los días que han transcurrido desde que presentaste tu solicitud de asilo.",
            62: "Conocer el conteo exacto de tu reloj te permite saber cuándo puedes aplicar para tu permiso de trabajo.",
            63: "Si tu reloj está detenido, existen formas de solicitar su reactivación con la orientación adecuada.",
            64: "Con solo $200 puedes recibir ayuda profesional para revisar tu carta y calcular tus días acumulados.",
            65: "USCIS actualiza el reloj automáticamente, pero es importante confirmar que esté corriendo correctamente.",
            66: "El reloj de asilo comienza a contar desde el momento en que USCIS recibe tu solicitud.",
            67: "Revisar tu carta a tiempo evita confusiones y retrasos en tu permiso de trabajo.",
            68: "Nuestro equipo te guía paso a paso para verificar que tu reloj esté activo y correctamente contado.",
            69: "Muchos solicitantes desconocen cuántos días acumularon, lo cual retrasa la solicitud del permiso.",
            70: "La carta de reloj es un documento esencial que demuestra tu avance dentro del proceso de asilo.",
            71: "Si tu reloj se detuvo, podemos ayudarte a identificar la causa y cómo reactivarlo.",
            72: "Una correcta revisión de tu carta puede acelerar tu elegibilidad para trabajar legalmente.",
            73: "Nuestro acompañamiento asegura que tu caso de asilo y tu reloj estén en sincronía.",
            74: "Los 180 días de reloj son la clave para obtener tu permiso de trabajo.",
            75: "Presentar tu solicitud sin revisar el reloj puede causar demoras innecesarias.",
            76: "Con asesoría profesional, puedes comprender cada parte del conteo y sus implicaciones.",
            77: "Mantener tu reloj activo es esencial para no perder tiempo en tu proceso migratorio.",
            78: "Acompañarte en este trámite es ayudarte a avanzar hacia tu estabilidad laboral y migratoria.",
            79: "Un análisis adecuado de tu reloj te da claridad, confianza y control sobre tu proceso.",
            80: "Saber exactamente cuántos días llevas te acerca un paso más a tu permiso de trabajo 😊"
        }
    },
    "VISAS B1/B2": {
        "días": {
            1: "Hola, qué gusto saludarte. ¿Qué te motivó a comenzar el trámite para tu visa americana?",
            2: "¡Buenos días! ¿Qué te gustaría lograr con tu visa, viajar por turismo o por negocios?",
            3: "Hola, ¿cómo te sientes con la idea de aplicar para la visa B1/B2?",
            4: "¡Hola! ¿Qué dudas tienes sobre el proceso de solicitud?",
            5: "Hola, ¿qué te impulsó a dar el paso de buscar acompañamiento profesional?",
            6: "¡Buenos días! ¿Qué parte del proceso te gustaría entender mejor antes de comenzar?",
            7: "Hola, ¿ya habías intentado obtener la visa antes o es tu primera vez?",
            8: "¡Hola! ¿Qué te gustaría revisar primero: el formulario o la cita consular?",
            9: "Hola, ¿qué te hace sentir más nervioso o emocionado de este trámite?",
            10: "Hola, ¿qué te gustaría lograr con el acompañamiento de nuestro equipo en tu proceso de visa?"
        },
        "semana_1": {
            11: "Hola 😊, ¿cómo te ha ido con el llenado del formulario DS-160?",
            12: "¡Buenos días! ¿Qué parte del formulario te gustaría repasar juntos?",
            13: "Hola, ¿qué dudas te surgieron sobre los documentos requeridos?",
            14: "¡Hola! ¿Qué te gustaría saber sobre los tiempos de cita en tu país?",
            15: "Hola 😊, ¿cómo te gustaría que te guiemos en tu preparación para la entrevista?",
            16: "¡Buenos días! ¿Qué detalle te gustaría confirmar antes de enviar tu solicitud?",
            17: "Hola, ¿qué obstáculo has encontrado en el proceso hasta ahora?",
            18: "¡Hola! ¿Qué parte del trámite te gustaría hacer más fácil y rápida?",
            19: "Hola, ¿qué tipo de viaje estás planeando realizar cuando obtengas tu visa?",
            20: "Hola 😊, ¿qué día te gustaría que revisemos juntos tu formulario?"
        },
        "semana_2_3": {
            21: "Hola, ¿cómo avanza tu proceso de solicitud de visa?",
            22: "¡Buenos días! ¿Qué avances lograste desde la última vez que hablamos?",
            23: "Hola, ¿qué parte de la preparación te gustaría reforzar antes de tu entrevista?",
            24: "¡Hola! ¿Qué te gustaría saber sobre las preguntas más comunes del consulado?",
            25: "Hola 😊, ¿qué documento te falta reunir para completar tu solicitud?",
            26: "¡Buenos días! ¿Qué expectativas tienes para tu cita?",
            27: "Hola, ¿qué te ayudaría a sentirte más preparado para tu entrevista?",
            28: "Hola, ¿qué detalles te gustaría confirmar sobre el pago o la cita consulta?",
            29: "¡Hola! 😊 ¿Qué te gustaría repasar antes de presentarte ante el oficial?",
            30: "Hola, ¿qué aspecto del proceso te genera más dudas en este momento?"
        },
        "mes_1": {
            31: "Hola, ¿cómo ha sido tu experiencia con el trámite de visa hasta ahora?",
            32: "¡Buenos días! ¿Qué parte del proceso te gustaría mejorar o actualizar?",
            33: "Hola, ¿qué aprendiste durante la preparación para tu entrevista?",
            34: "Hola, ¿qué te gustaría revisar antes de tu cita en la embajada?",
            35: "Hola, ¿qué te ha resultado más fácil o más complicado de este proceso?",
            36: "¡Hola! ¿Qué te gustaría lograr este mes con tu trámite?",
            37: "Hola, ¿qué parte del formulario te gustaría que revisemos juntos?",
            38: "¡Buenos días! ¿Qué documentos pendientes te gustaría reunir esta semana?",
            39: "Hola, ¿qué información te gustaría tener para sentirte más tranquilo antes de la cita?",
            40: "Hola, ¿qué te gustaría mejorar en tu preparación para aumentar tus posibilidades?"
        },
        "mes_2_3": {
            41: "Hola, ha pasado un tiempo desde la última vez. ¿Qué avances has tenido con tu solicitud de visa?",
            42: "¡Hola! ¿Qué te gustaría retomar para continuar tu trámite?",
            43: "Hola, ¿cómo te sientes con los avances de tu proceso hasta ahora?",
            44: "¡Buenos días! ¿Qué nuevos pasos te gustaría completar este mes?",
            45: "Hola, ¿qué apoyo te ayudaría a fortalecer tu caso antes de presentarte a la entrevista?",
            46: "Hola 😊, ¿qué dudas te gustaría resolver sobre los requisitos actuales?",
            47: "¡Hola! 😊 ¿Qué te gustaría lograr antes de finalizar tu trámite?",
            48: "Buenos días, ¿qué información te gustaría que te comparta sobre el seguimiento de tu caso?",
            49: "Hola, ¿qué parte de tu proceso consideras más importante reforzar ahora?",
            50: "Hola 😊, ¿qué meta tienes para concluir tu trámite con éxito?"
        },
        "mes_4_5": {
            51: "Hola 😊, ¿cómo has estado? ¿Qué parte del trámite te gustaría retomar?",
            52: "¡Buenos días! ¿Qué novedades has tenido con tu proceso desde la última vez?",
            53: "Hola 😊, ¿qué paso te gustaría completar esta semana para retomar tu visa?",
            54: "Hola, ¿qué detalle te gustaría verificar sobre tu cita o estatus actual?",
            55: "¡Hola! 😊 ¿Qué te motivó a iniciar tu trámite y qué te gustaría lograr ahora?",
            56: "Buenos días, recuerda que con solo $200 puedes avanzar con tu proceso de visa con orientación profesional.",
            57: "Hola 😊, ¿qué te inspira a continuar con tu solicitud?",
            58: "¡Hola! 😊 Me alegra saludarte. ¿Qué apoyo te gustaría recibir para concluir tu trámite?",
            59: "Hola 😊, ¿qué expectativas tienes sobre tu próxima cita consular?",
            60: "Buenos días, ¿cómo te gustaría que te acompañemos en esta etapa final de tu proceso?"
        },
        "valor": {
            61: "Prepararte adecuadamente para la entrevista aumenta tus posibilidades de aprobación.",
            62: "Con solo $200 puedes recibir asistencia completa para llenar tu formulario DS-160 sin errores.",
            63: "Tener tus documentos en orden demuestra organización y genera buena impresión ante el oficial.",
            64: "La claridad en tus respuestas durante la entrevista es clave para un resultado positivo.",
            65: "Nuestro equipo te guía paso a paso para evitar errores en el formulario y el pago.",
            66: "Muchos rechazos ocurren por errores simples que pueden evitarse con orientación profesional.",
            67: "Una solicitud bien estructurada refleja honestidad y confianza ante el consulado.",
            68: "Te ayudamos a practicar las preguntas más frecuentes de la entrevista para que llegues seguro.",
            69: "El acompañamiento profesional puede ahorrarte tiempo y errores costosos.",
            70: "Tener asesoría personalizada te permite entender exactamente qué espera el oficial en tu cita.",
            71: "Una visa aprobada te abre oportunidades de viajar, aprender y crecer personal o profesionalmente.",
            72: "Los consulados valoran la coherencia en tu información y propósito de viaje.",
            73: "Con orientación experta, puedes preparar tu entrevista sin estrés y con claridad.",
            74: "Cada detalle cuenta: desde la foto hasta la información del formulario DS-160.",
            75: "Saber cómo responder las preguntas clave te da confianza durante la cita.",
            76: "Nuestro equipo revisa toda tu información antes de enviar tu solicitud.",
            77: "Una preparación adecuada transforma la ansiedad en seguridad durante tu entrevista.",
            78: "Te ayudamos a gestionar todo el proceso, desde el formulario hasta la confirmación de cita.",
            79: "Una inversión pequeña hoy puede evitar rechazos y pérdidas de dinero en el futuro.",
            80: "La preparación es la clave del éxito en tu solicitud de visa. Con nuestro apoyo, puedes lograrlo 😊"
        }
    },
    "GENÉRICOS UNIVERSALES": {
        "días": {
            1: "Hola, qué gusto saludarte. ¿En qué trámite estás pensando avanzar?",
            2: "¡Buenos días! Me alegra saber de ti. ¿Qué tipo de proceso migratorio te interesa realizar?",
            3: "Hola, ¿cómo te ha ido? ¿Qué te motivó a escribirnos hoy?",
            4: "¡Hola! ¿Qué objetivo te gustaría alcanzar con tu trámite migratorio?",
            5: "Hola, ¿qué información te gustaría conocer para tomar tu próxima decisión?",
            6: "¡Buenos días! ¿Qué parte del proceso te gustaría que te explique mejor?",
            7: "Hola, ¿qué tipo de apoyo estás buscando en este momento?",
            8: "¡Hola! ¿Qué dudas te gustaría aclarar antes de comenzar tu trámite?",
            9: "Hola, ¿cómo te sientes con tu situación actual?",
            10: "Hola, ¿qué te gustaría lograr con la ayuda de nuestro equipo?"
        },
        "semana_1": {
            11: "Hola, ¿cómo te ha ido desde la última vez que hablamos?",
            12: "¡Buenos días! ¿Qué avances lograste con tu trámite o tu planificación?",
            13: "Hola, ¿qué parte del proceso te gustaría revisar conmigo?",
            14: "¡Hola! ¿Qué información necesitas para sentirte más seguro al continuar?",
            15: "Hola, ¿cómo te gustaría que te acompañemos durante este proceso?",
            16: "¡Buenos días! ¿Qué paso te gustaría dar primero para avanzar?",
            17: "Hola, ¿qué dudas o preocupaciones te surgieron en estos días?",
            18: "¡Hola! ¿Qué tipo de trámite tienes en mente o te gustaría comenzar?",
            19: "Hola, ¿qué experiencia has tenido con procesos migratorios en el pasado?",
            20: "Hola, ¿qué te animaría a iniciar tu trámite esta semana?"
        },
        "semana_2_3": {
            21: "Hola, ¿cómo va tu proceso o tu decisión de iniciar un trámite?",
            22: "¡Buenos días! ¿Qué información te gustaría tener antes de avanzar?",
            23: "Hola, ¿qué parte del proceso te parece más complicada o confusa?",
            24: "¡Hola! ¿Qué te gustaría saber sobre los tipos de trámites que manejamos?",
            25: "Hola, ¿qué meta personal te gustaría cumplir con tu proceso migratorio?",
            26: "¡Buenos días! ¿Qué paso crees que podrías dar para avanzar más rápido?",
            27: "Hola, ¿qué dudas te gustaría aclarar sobre los servicios disponibles?",
            28: "Hola, ¿qué apoyo te haría sentir acompañado durante tu trámite?",
            29: "¡Hola! ¿Qué plan tienes para avanzar con tu caso en los próximos días?",
            30: "Hola, ¿qué te gustaría que preparemos para ayudarte a comenzar?"
        },
        "mes_1": {
            31: "Hola, ¿cómo ha sido tu experiencia con nosotros hasta ahora?",
            32: "¡Buenos días! ¿Qué parte de tu trámite te gustaría revisar o actualizar?",
            33: "Hola, ¿qué avances lograste con tu proceso en las últimas semanas?",
            34: "Hola, ¿qué cambios han ocurrido en tu situación que debamos tener en cuenta?",
            35: "Hola, ¿cómo te sientes con los pasos que has dado hasta hoy?",
            36: "¡Hola! ¿Qué te gustaría lograr en este mes con tu caso?",
            37: "Hola, ¿qué información te gustaría revisar para seguir avanzando con confianza?",
            38: "¡Buenos días! ¿Qué meta te gustaría alcanzar en tu trámite durante este mes?",
            39: "Hola, ¿qué te haría sentir más seguro o acompañado en este proceso?",
            40: "Hola, ¿qué parte del proceso te gustaría hacer más simple o rápida?"
        },
        "mes_2_3": {
            41: "Hola, ha pasado un tiempo desde la última vez. ¿Cómo va tu proceso?",
            42: "¡Hola! ¿Qué avances tuviste o qué te gustaría retomar esta semana?",
            43: "Hola, ¿qué cambios has tenido desde que comenzaste tu trámite?",
            44: "¡Buenos días! ¿Qué información te gustaría que te actualice sobre los procesos actuales?",
            45: "Hola, ¿qué parte de tu trámite te gustaría reforzar con ayuda profesional?",
            46: "Hola, ¿qué te ha resultado más sencillo o más difícil de este proceso?",
            47: "¡Hola! ¿Qué meta te gustaría cumplir este mes con tu caso?",
            48: "Buenos días, ¿qué te gustaría saber sobre las opciones que tienes disponibles ahora?",
            49: "Hola, ¿qué paso te falta completar para sentirte tranquilo con tu trámite?",
            50: "Hola, ¿qué te gustaría revisar para retomar tu proceso con confianza?"
        },
        "mes_4_5": {
            51: "Hola, ¿cómo has estado? ¿Qué trámite te gustaría retomar o actualizar?",
            52: "¡Buenos días! ¿Qué novedades has tenido desde la última vez que hablamos?",
            53: "Hola, ¿qué te gustaría lograr en las próximas semanas con tu proceso?",
            54: "Hola, ¿qué te inspiró a comenzar y cómo te gustaría continuar ahora?",
            55: "¡Hola! ¿Qué paso te gustaría dar para avanzar en tu trámite?",
            56: "Buenos días, con solo $200 puedes retomar tu trámite y hacerlo de forma segura.",
            57: "Hola, ¿qué te motiva a continuar con tus planes migratorios?",
            58: "¡Hola! Me alegra saludarte. ¿Qué te gustaría revisar o actualizar esta semana?",
            59: "Hola, ¿qué parte de tu trámite te gustaría fortalecer con orientación profesional?",
            60: "Buenos días, ¿cómo te gustaría que te acompañemos en esta nueva etapa?"
        },
        "valor": {
            61: "Con acompañamiento profesional, cualquier trámite se vuelve más claro, rápido y seguro.",
            62: "Nuestro equipo te guía paso a paso para que no cometas errores ni pierdas tiempo.",
            63: "Con solo $200 puedes iniciar tu proceso con asesoría completa y personalizada.",
            64: "Cada caso es único, por eso te brindamos orientación adaptada a tu situación.",
            65: "Evitar errores al inicio del trámite puede ahorrarte meses de espera.",
            66: "Con nosotros, cada paso que des tendrá respaldo profesional y claridad total.",
            67: "La clave para avanzar con éxito es tener tus documentos y estrategias bien preparadas.",
            68: "Nuestro objetivo es que cada cliente se sienta acompañado, informado y tranquilo.",
            69: "No necesitas hacerlo solo: con orientación correcta, todo es más sencillo.",
            70: "Una consulta a tiempo puede evitarte rechazos o retrasos en el futuro.",
            71: "Nuestro equipo está comprometido con tu progreso y estabilidad migratoria.",
            72: "Con asesoría personalizada, tu proceso se adapta a tus necesidades reales.",
            73: "Iniciar tu trámite con acompañamiento profesional te da seguridad desde el primer paso.",
            74: "Cada avance en tu caso te acerca a tus metas personales y familiares.",
            75: "Evitar errores pequeños marca una gran diferencia en el resultado de tu trámite.",
            76: "Ofrecemos un acompañamiento humano, cercano y accesible para cada caso.",
            77: "Nuestro compromiso es ayudarte a lograr resultados reales, paso a paso.",
            78: "Con orientación profesional, todo proceso migratorio se vuelve más predecible y claro.",
            79: "Con solo $200 puedes comenzar el trámite que más se ajuste a tu situación actual.",
            80: "Tu futuro migratorio comienza con una decisión: dejarte acompañar por quienes saben ayudarte 😊"
        }
    }
};

module.exports = tramites
